Collapsible doc sections
flyway/flywaydb.org pull request #222
Opened 2020-09-28 16:16 UTC by DoodleBobBuffPants

2020-09-28 16:18 UTC, Lyeeedar commented
Currently it collapses whenever you change page. Could we get it to remember the expansion / collapse status as you transition around the site?

2020-09-28 16:24 UTC, DoodleBobBuffPants commented
Currently it'll work for some and not for all. It sets the `open` prop on `<details></details>` tags based on the URL, so for databases for example we can tell whether the section should be open by checking the URL, because there isn't any built in support for this. Other sections don't have a common URL prefix to tell them apart, so we'd either need to refactor the pages or add a Liquid variable for each section

2020-09-29 10:55 UTC, Lyeeedar commented
https://idratherbewriting.com/documentation-theme-jekyll/mydoc_sidebar_navigation.html worth investigating?

2020-09-29 14:19 UTC, DoodleBobBuffPants commented
> https://idratherbewriting.com/documentation-theme-jekyll/mydoc_sidebar_navigation.html worth investigating?

It seems like it's a website template instead of an actual theme

2020-09-29 16:18 UTC, Lyeeedar requested changes
Could we change `/documentation/configuration/configuration` to `/documentation/configuration/parameters`?

2020-09-29 16:18 UTC, Lyeeedar commented on documentation/usage/maven/index.md
> +[Config files](/documentation/configuration/configfiles) are supported by the Flyway Maven plugin. If you are not familiar with them,
All these links to the `configfiles` page should be `configFiles` (might have been originally broken by my commit, but should get fixed anyway)

2020-09-30 12:48 UTC, Lyeeedar approved these changes

2020-09-30 15:22 UTC, MikielAgutu requested changes
We have to be careful with broken links.

For instance, `/documentation/configuration/` has moved to `documentation/configuration/parameters/`. However there's no redirect. We need to introduce redirects to preserve old links.

2020-09-30 16:02 UTC, DoodleBobBuffPants commented
> We have to be careful with broken links.
> 
> For instance, `/documentation/configuration/` has moved to `documentation/configuration/parameters/`. However there's no redirect. We need to introduce redirects to preserve old links.

Is this referring to broken links within the website? Instead of redirected they should be updated

2020-10-01 09:28 UTC, MikielAgutu commented
Sorry, let me clarify.

When I say 'broken links' you can think of it like a breaking change to the 'API' of the website. Except in this case the API is the url.

At the moment `https://flywaydb.org/documentation/configuration/` is a valid location on the website. However, if this change goes in, that same url will link to an invalid page. So that location will be 'broken'.

This is a problem because web links tend to die hard. For instance, when we respond to customers on GitHub we often link to the docs. If those links suddenly stop working that's a problem because people tend to visit such posts years after they're created.

How many times have you visited a Stack Overflow post that happens to be years old? Wouldn't it be annoying if the +100 verified answer was link to a docs page that no longer exists?

The solution is to introduce sensible redirects for locations that have been deprecated. In this case `documentation/configuration/` ought to be redirected to `documentation/configuration/parameters/` since that's the equivalent page. Jekyll does support redirects, though I think you need to use a plugin (maybe https://github.com/jekyll/jekyll-redirect-from).

2020-10-05 13:48 UTC, Lyeeedar requested changes
- Currently if you select the 'errorOverrides', 'callbacks', or 'dry runs' pages from either `get started/advanced` or `concepts`, both pages in the menu show as selected, suggesting they are the same page (even though they arent).

  - On that topic, we should probably link from the concepts pages to the get started/advanced ones (under a `see example tutorial` or `learn more about this`) as the tutorials seems pretty useful + give good use cases.

- `Config files` link in `configuration` is broken.

- Sub menu padding is really high + the lack of background makes it look a little messy. Could we reduce the padding / add background to the submenus?

2020-10-06 09:39 UTC, MikielAgutu commented
![image](https://user-images.githubusercontent.com/20282448/95185084-2f15b880-07c0-11eb-965d-2857b4f24988.png)
Sub headings are in line with the top level heading

2020-10-06 10:30 UTC, MikielAgutu approved these changes
🚀

2020-10-06 10:35 UTC, Lyeeedar approved these changes

2020-10-06 10:41 UTC, merged