Clarifications around "target"
flyway/flywaydb.org pull request #293
Opened 2021-03-15 11:19 UTC by juliahayward

2021-03-15 11:24 UTC, DoodleBobBuffPants requested changes
Looks good, minor comment on wording

Since this is markdown, we should use backticks instead of `<code></code>` tags too

2021-03-15 11:24 UTC, DoodleBobBuffPants commented on documentation/configuration/parameters/target.md
> +<code>latest</code> for migrations, <code>current</code> for undos.
I think it would be clearer if we wrote `versioned migrations` and `undo migrations` since they're both a type of migration

2021-03-15 11:25 UTC, madninjaskillz commented on documentation/configuration/parameters/target.md
> +higher version number will be ignored. If the target is <code>current</code>, then no versioned migrations will be
should this not be 
`code`
as per above? I guess html would work here but we should probably stick to markdown when its available.

2021-03-18 09:24 UTC, DoodleBobBuffPants approved these changes

2021-03-18 09:25 UTC, merged