Add docs for `failOnMissingLocations`
flyway/flywaydb.org pull request #315
Opened 2021-05-04 15:10 UTC by MikielAgutu

2021-05-04 16:22 UTC, DoodleBobBuffPants requested changes

2021-05-04 16:22 UTC, DoodleBobBuffPants commented on documentation/configuration/configfile.md
> +
We don't need to/shouldn't manually update the conf in this file - the release notes automater will do it for us

2021-05-04 16:22 UTC, DoodleBobBuffPants commented on documentation/configuration/parameters/failOnMissingLocations.md
> +redirect_from: /documentation/configuration/failOnMissingLocations/
New pages don't need a redirect (there won't be anything to redirect from)

2021-05-05 09:33 UTC, DoodleBobBuffPants approved these changes

2021-05-09 17:10 UTC, YoutacRSVARs approved these changes

2021-05-13 15:37 UTC, merged