Add new maven and gradle repositories to examples
flyway/flywaydb.org pull request #457
Opened 2022-06-27 12:21 UTC by Barry-RG

2022-06-27 12:35 UTC, DoodleBobBuffPants requested changes

2022-06-27 12:35 UTC, DoodleBobBuffPants commented on documentation/usage/api/index.md
> +        &lt;version&gt;{{ site.flywayVersion }}&lt;/version&gt;
I think this should be `site.flywayPreviewVersion`?

2022-06-27 12:35 UTC, DoodleBobBuffPants commented on documentation/usage/api/index.md
> +compile "org.flywaydb<strong>.enterprise</strong>:flyway-core:{{ site.flywayVersion }}"
I think this should be `site.flywayPreviewVersion`?

2022-06-27 12:35 UTC, DoodleBobBuffPants commented on documentation/usage/maven/index.md
> +        &lt;version&gt;{{ site.flywayVersion }}&lt;/version&gt;
I think this should be `site.flywayPreviewVersion`?

2022-06-27 12:35 UTC, DoodleBobBuffPants commented on documentation/usage/maven/index.md
> +        &lt;version&gt;{{ site.flywayVersion }}&lt;/version&gt;
I think this should be `site.flywayPreviewVersion`?

2022-06-27 12:36 UTC, angellaa commented
We need to add legal text on each page close to the point when the user download/use the teams/enterprise APIs...

Alongs the lines:
By "downloading Flyway Teams" you confirm that you have read and agree to the terms of the [Redgate EULA](https://www.red-gate.com/assets/purchase/assets/subscription-license.pdf?_ga=2.265045707.556964523.1656332792-1685764737.1620948215).

2022-06-27 13:08 UTC, DoodleBobBuffPants requested changes
All looks good, one minor thing about spacing

2022-06-27 13:08 UTC, DoodleBobBuffPants commented on documentation/usage/api/index.md
> +compile "org.flywaydb<strong>.enterprise</strong>:flyway-core:{{ site.flywayVersion }}"
I think this `compile` line needs to be spaced in a bit so it's indented w.r.t. `dependencies`

2022-06-27 13:20 UTC, DoodleBobBuffPants approved these changes

2022-06-30 13:42 UTC, madninjaskillz approved these changes

2022-06-30 13:42 UTC, merged